#!/bin/bash
stl2dae=/data/_Data/Research/Myorobotics/ws/caliper/contrib/stl2dae/stl2dae
echo "Converting p-becken-v06.STL"
$stl2dae "p-becken-v06.STL" "p-becken-v06.dae" "Steel"
echo "Converting p-halterreferenz-rechts-v04.STL"
$stl2dae "p-halterreferenz-rechts-v04.STL" "p-halterreferenz-rechts-v04.dae" ""
echo "Converting z-jfm-0608-06-v01.STL"
$stl2dae "z-jfm-0608-06-v01.STL" "z-jfm-0608-06-v01.dae" "Steel"
echo "Converting z-induktiv-sensor-v01.STL"
$stl2dae "z-induktiv-sensor-v01.STL" "z-induktiv-sensor-v01.dae" "Steel"
echo "Converting p-federstoessel-v01.STL"
$stl2dae "p-federstoessel-v01.STL" "p-federstoessel-v01.dae" "SolidWorks_DIN_Materials_1.0037_(S235JR)_165"
echo "Converting p-halterdeckel-rechts-v02.STL"
$stl2dae "p-halterdeckel-rechts-v02.STL" "p-halterdeckel-rechts-v02.dae" "Steel"
echo "Converting z-passschraube-misumi-4-v01.STL"
$stl2dae "z-passschraube-misumi-4-v01.STL" "z-passschraube-misumi-4-v01.dae" "Steel"
echo "Converting Lock_washer_DIN_6799_-_7.STL"
$stl2dae "Lock_washer_DIN_6799_-_7.STL" "Lock_washer_DIN_6799_-_7.dae" ""
echo "Converting Hexagon_Nut_ISO_4032_-_M2.5_-_W_-_N.STL"
$stl2dae "Hexagon_Nut_ISO_4032_-_M2.5_-_W_-_N.STL" "Hexagon_Nut_ISO_4032_-_M2.5_-_W_-_N.dae" ""
echo "Converting DIN_7991_-_M3_x_8_---_4.8C.STL"
$stl2dae "DIN_7991_-_M3_x_8_---_4.8C.STL" "DIN_7991_-_M3_x_8_---_4.8C.dae" ""
echo "Converting p-oese-v01.STL"
$stl2dae "p-oese-v01.STL" "p-oese-v01.dae" "SolidWorks_DIN_Materials_1.0037_(S235JR)_165"
echo "Converting Hexagon_Thin_Nut_ISO_4035_-_M12_-_N.STL"
$stl2dae "Hexagon_Thin_Nut_ISO_4035_-_M12_-_N.STL" "Hexagon_Thin_Nut_ISO_4035_-_M12_-_N.dae" ""
echo "Converting z-feder-febrotec-v01.STL"
$stl2dae "z-feder-febrotec-v01.STL" "z-feder-febrotec-v01.dae" "Steel"
echo "Converting p-seil-v02.STL"
$stl2dae "p-seil-v02.STL" "p-seil-v02.dae" "Steel"
echo "Converting p-umlenkpulley-v06.STL"
$stl2dae "p-umlenkpulley-v06.STL" "p-umlenkpulley-v06.dae" "Steel"
echo "Converting Parallel_Pin_ISO_2338_-_4_h6_x_10_-_St.STL"
$stl2dae "Parallel_Pin_ISO_2338_-_4_h6_x_10_-_St.STL" "Parallel_Pin_ISO_2338_-_4_h6_x_10_-_St.dae" ""
echo "Converting z-Motor-Maxon-EC22-386673-v01.STL"
$stl2dae "z-Motor-Maxon-EC22-386673-v01.STL" "z-Motor-Maxon-EC22-386673-v01.dae" "Steel"
echo "Converting z-Getriebe-Maxon-GP22C_1-STUFIG-143972-v01.STL"
$stl2dae "z-Getriebe-Maxon-GP22C_1-STUFIG-143972-v01.STL" "z-Getriebe-Maxon-GP22C_1-STUFIG-143972-v01.dae" "Steel"
echo "Converting p-motorpulley-v04.STL"
$stl2dae "p-motorpulley-v04.STL" "p-motorpulley-v04.dae" "SolidWorks_DIN_Materials_1.4301_(X5CrNi18-10)_131"
echo "Converting DIN_913_-_M2_x_3-C.STL"
$stl2dae "DIN_913_-_M2_x_3-C.STL" "DIN_913_-_M2_x_3-C.dae" ""
echo "Converting p-absolutmess-plaettchen-v04.STL"
$stl2dae "p-absolutmess-plaettchen-v04.STL" "p-absolutmess-plaettchen-v04.dae" "SolidWorks_DIN_Materials_1.0037_(S235JR)_165"
echo "Converting ISO_2010_-_M2.5_x_10_---_10C.STL"
$stl2dae "ISO_2010_-_M2.5_x_10_---_10C.STL" "ISO_2010_-_M2.5_x_10_---_10C.dae" ""
echo "Converting p-gewindeeinsatz-v01.STL"
$stl2dae "p-gewindeeinsatz-v01.STL" "p-gewindeeinsatz-v01.dae" "SolidWorks_DIN_Materials_1.4301_(X5CrNi18-10)_131"
echo "Converting z-380264_epos2_24_2-v01.STL"
$stl2dae "z-380264_epos2_24_2-v01.STL" "z-380264_epos2_24_2-v01.dae" "Steel"
echo "Converting z-zyl-schr-schaft-M3x40-v01.STL"
$stl2dae "z-zyl-schr-schaft-M3x40-v01.STL" "z-zyl-schr-schaft-M3x40-v01.dae" "Steel"
echo "Converting Hexagon_Thin_Nut_ISO_4035_-_M3_-_C.STL"
$stl2dae "Hexagon_Thin_Nut_ISO_4035_-_M3_-_C.STL" "Hexagon_Thin_Nut_ISO_4035_-_M3_-_C.dae" ""
echo "Converting n-zyl-schr-i6kt-M2.5x8_(BN11).STL"
$stl2dae "n-zyl-schr-i6kt-M2.5x8_(BN11).STL" "n-zyl-schr-i6kt-M2.5x8_(BN11).dae" ""
echo "Converting p-halterreferenz-links-v04.STL"
$stl2dae "p-halterreferenz-links-v04.STL" "p-halterreferenz-links-v04.dae" ""
echo "Converting p-halterdeckel-links-v02.STL"
$stl2dae "p-halterdeckel-links-v02.STL" "p-halterdeckel-links-v02.dae" "Steel"
echo "Converting p-deckel-hueftgelenk-v01.STL"
$stl2dae "p-deckel-hueftgelenk-v01.STL" "p-deckel-hueftgelenk-v01.dae" "Steel"
echo "Converting z-igus-jsm-3034-30.STL"
$stl2dae "z-igus-jsm-3034-30.STL" "z-igus-jsm-3034-30.dae" "Steel"
echo "Converting zyl-schr-i6kt-M3x06_(BN4).STL"
$stl2dae "zyl-schr-i6kt-M3x06_(BN4).STL" "zyl-schr-i6kt-M3x06_(BN4).dae" ""
echo "Converting z-cpu-pITX-SP-v01.STL"
$stl2dae "z-cpu-pITX-SP-v01.STL" "z-cpu-pITX-SP-v01.dae" "Steel"
echo "Converting z-pcan-usb.STL"
$stl2dae "z-pcan-usb.STL" "z-pcan-usb.dae" "Steel"
echo "Converting z-usb-stecker-gross-v01.STL"
$stl2dae "z-usb-stecker-gross-v01.STL" "z-usb-stecker-gross-v01.dae" "Steel"
echo "Converting p-federtraeger-v01.STL"
$stl2dae "p-federtraeger-v01.STL" "p-federtraeger-v01.dae" "SolidWorks_DIN_Materials_1.4301_(X5CrNi18-10)_131"
echo "Converting n-tellerfeder-knoerzer-A0315.STL"
$stl2dae "n-tellerfeder-knoerzer-A0315.STL" "n-tellerfeder-knoerzer-A0315.dae" "Steel"
echo "Converting p-stuetzscheibe-v01.STL"
$stl2dae "p-stuetzscheibe-v01.STL" "p-stuetzscheibe-v01.dae" "SolidWorks_DIN_Materials_1.4301_(X5CrNi18-10)_131"
echo "Converting p-spannscheibe-v01.STL"
$stl2dae "p-spannscheibe-v01.STL" "p-spannscheibe-v01.dae" "SolidWorks_DIN_Materials_1.4301_(X5CrNi18-10)_131"
echo "Converting zyl-schr-i6kt-M4x12_(BN4).STL"
$stl2dae "zyl-schr-i6kt-M4x12_(BN4).STL" "zyl-schr-i6kt-M4x12_(BN4).dae" ""
echo "Converting p-deckel-wirbelspanner-v01.STL"
$stl2dae "p-deckel-wirbelspanner-v01.STL" "p-deckel-wirbelspanner-v01.dae" ""
echo "Converting se-schr-i6kt-m2x08_(BN20).STL"
$stl2dae "se-schr-i6kt-m2x08_(BN20).STL" "se-schr-i6kt-m2x08_(BN20).dae" ""
echo "Converting zyl-schr-i6kt-M2x08_(BN4).STL"
$stl2dae "zyl-schr-i6kt-M2x08_(BN4).STL" "zyl-schr-i6kt-M2x08_(BN4).dae" ""
echo "Converting z-molex-026013096.STL"
$stl2dae "z-molex-026013096.STL" "z-molex-026013096.dae" "Steel"
echo "Converting z-molex-039012120.STL"
$stl2dae "z-molex-039012120.STL" "z-molex-039012120.dae" "Steel"
echo "Converting p-oberschenkel-v02.STL"
$stl2dae "p-oberschenkel-v02.STL" "p-oberschenkel-v02.dae" "Steel"
echo "Converting p-unterschenkel-v02.STL"
$stl2dae "p-unterschenkel-v02.STL" "p-unterschenkel-v02.dae" "Steel"
echo "Converting p-fuss-rechts-v12.STL"
$stl2dae "p-fuss-rechts-v12.STL" "p-fuss-rechts-v12.dae" "Steel"
echo "Converting senk-schr-i6kt_M3x10.STL"
$stl2dae "senk-schr-i6kt_M3x10.STL" "senk-schr-i6kt_M3x10.dae" ""
echo "Converting zyl-schr_M5x30_(BN4).STL"
$stl2dae "zyl-schr_M5x30_(BN4).STL" "zyl-schr_M5x30_(BN4).dae" ""
echo "Converting 6-kt-mutter_M5.STL"
$stl2dae "6-kt-mutter_M5.STL" "6-kt-mutter_M5.dae" ""
echo "Converting p-fuss-links-v12.STL"
$stl2dae "p-fuss-links-v12.STL" "p-fuss-links-v12.dae" "Steel"
echo "Converting p-gelenkhuelse-v01.STL"
$stl2dae "p-gelenkhuelse-v01.STL" "p-gelenkhuelse-v01.dae" "SolidWorks_DIN_Materials_1.4301_(X5CrNi18-10)_131"
echo "Converting z-igus-jsm-0810-04.STL"
$stl2dae "z-igus-jsm-0810-04.STL" "z-igus-jsm-0810-04.dae" "Steel"
echo "Converting p-kreuzachse-v01.STL"
$stl2dae "p-kreuzachse-v01.STL" "p-kreuzachse-v01.dae" "Steel"
echo "Converting p-oberschenkelachse-v01.STL"
$stl2dae "p-oberschenkelachse-v01.STL" "p-oberschenkelachse-v01.dae" "SolidWorks_DIN_Materials_1.4301_(X5CrNi18-10)_131"
echo "Converting p-gelenkkugel_25mm.STL"
$stl2dae "p-gelenkkugel_25mm.STL" "p-gelenkkugel_25mm.dae" "Steel"
echo "Converting p-lendenwirbel-1.STL"
$stl2dae "p-lendenwirbel-1.STL" "p-lendenwirbel-1.dae" "Steel"
echo "Converting Washer_DIN_9021_-_5.3.STL"
$stl2dae "Washer_DIN_9021_-_5.3.STL" "Washer_DIN_9021_-_5.3.dae" ""
echo "Converting p-lendenwirbel-2.1_rotation.STL"
$stl2dae "p-lendenwirbel-2.1_rotation.STL" "p-lendenwirbel-2.1_rotation.dae" "Steel"
echo "Converting p-axialnadellager.STL"
$stl2dae "p-axialnadellager.STL" "p-axialnadellager.dae" "Steel"
echo "Converting p-zapfen_rotation.STL"
$stl2dae "p-zapfen_rotation.STL" "p-zapfen_rotation.dae" "SolidWorks_DIN_Materials_1.0037_(S235JR)_165"
echo "Converting p-lendenwirbel-2.2_rotation.STL"
$stl2dae "p-lendenwirbel-2.2_rotation.STL" "p-lendenwirbel-2.2_rotation.dae" "Steel"
echo "Converting p-Druckfeder_Gutekunst_D_288T_03.STL"
$stl2dae "p-Druckfeder_Gutekunst_D_288T_03.STL" "p-Druckfeder_Gutekunst_D_288T_03.dae" "Steel"
echo "Converting p-feder-lendenrotation.STL"
$stl2dae "p-feder-lendenrotation.STL" "p-feder-lendenrotation.dae" "Steel"
echo "Converting p-lendenwirbel-3_anbindung_wirbelsaeule.STL"
$stl2dae "p-lendenwirbel-3_anbindung_wirbelsaeule.STL" "p-lendenwirbel-3_anbindung_wirbelsaeule.dae" "Steel"
echo "Converting p-zapfen-Wirbelsaeule.STL"
$stl2dae "p-zapfen-Wirbelsaeule.STL" "p-zapfen-Wirbelsaeule.dae" "SolidWorks_DIN_Materials_1.4301_(X5CrNi18-10)_131"
echo "Converting p-Seilzug_110mm.STL"
$stl2dae "p-Seilzug_110mm.STL" "p-Seilzug_110mm.dae" "Steel"
echo "Converting p-spannhuelse-1.STL"
$stl2dae "p-spannhuelse-1.STL" "p-spannhuelse-1.dae" "Benutzerdefinierte_Materialien_Stahl_293"
echo "Converting Hexagon_Nut_ISO_4032_-_M4_-_W_-_N.STL"
$stl2dae "Hexagon_Nut_ISO_4032_-_M4_-_W_-_N.STL" "Hexagon_Nut_ISO_4032_-_M4_-_W_-_N.dae" ""
echo "Converting p-zugaretierung-zapfen.STL"
$stl2dae "p-zugaretierung-zapfen.STL" "p-zugaretierung-zapfen.dae" "Steel"
echo "Converting p-PT-schraube-3x8.STL"
$stl2dae "p-PT-schraube-3x8.STL" "p-PT-schraube-3x8.dae" "Steel"
echo "Converting p-halterreferenz-oa-v02-bauch.STL"
$stl2dae "p-halterreferenz-oa-v02-bauch.STL" "p-halterreferenz-oa-v02-bauch.dae" ""
echo "Converting p-halterdeckel-2-v01.STL"
$stl2dae "p-halterdeckel-2-v01.STL" "p-halterdeckel-2-v01.dae" "Steel"
echo "Converting z-feder-durovis-62-3-2-v01.STL"
$stl2dae "z-feder-durovis-62-3-2-v01.STL" "z-feder-durovis-62-3-2-v01.dae" "Steel"
echo "Converting p-seil-v01.STL"
$stl2dae "p-seil-v01.STL" "p-seil-v01.dae" "Steel"
echo "Converting Sechskantmutter_ISO934-M3.STL"
$stl2dae "Sechskantmutter_ISO934-M3.STL" "Sechskantmutter_ISO934-M3.dae" ""
echo "Converting p-umlenkhuelse-bauch.STL"
$stl2dae "p-umlenkhuelse-bauch.STL" "p-umlenkhuelse-bauch.dae" "Steel"
echo "Converting z-gp16-401954-v01.STL"
$stl2dae "z-gp16-401954-v01.STL" "z-gp16-401954-v01.dae" "Steel"
echo "Converting z-EC16-405813-v01.STL"
$stl2dae "z-EC16-405813-v01.STL" "z-EC16-405813-v01.dae" "Steel"
echo "Converting p-motorpulley-v03.STL"
$stl2dae "p-motorpulley-v03.STL" "p-motorpulley-v03.dae" "SolidWorks_DIN_Materials_3.0205_(EN-AW_1200)_258"
echo "Converting Senkschraube_mit_Innensechsrund_M2x10_(BN4851).STL"
$stl2dae "Senkschraube_mit_Innensechsrund_M2x10_(BN4851).STL" "Senkschraube_mit_Innensechsrund_M2x10_(BN4851).dae" ""
echo "Converting z-epos2-24-2-v01.STL"
$stl2dae "z-epos2-24-2-v01.STL" "z-epos2-24-2-v01.dae" "Steel"
echo "Converting p_NEW_H1.STL"
$stl2dae "p_NEW_H1.STL" "p_NEW_H1.dae" "Steel"
echo "Converting p_NEW_Kreuz.STL"
$stl2dae "p_NEW_Kreuz.STL" "p_NEW_Kreuz.dae" "Steel"
echo "Converting p_NEW_H2.STL"
$stl2dae "p_NEW_H2.STL" "p_NEW_H2.dae" "Steel"
echo "Converting p-Bolzen_Hals.STL"
$stl2dae "p-Bolzen_Hals.STL" "p-Bolzen_Hals.dae" "Steel"
echo "Converting a-axialnadellager.STL"
$stl2dae "a-axialnadellager.STL" "a-axialnadellager.dae" "Steel"
echo "Converting p_NEW_H3.STL"
$stl2dae "p_NEW_H3.STL" "p_NEW_H3.dae" "Steel"
echo "Converting p_NEW_Motorenhalterung_H2.STL"
$stl2dae "p_NEW_Motorenhalterung_H2.STL" "p_NEW_Motorenhalterung_H2.dae" "Steel"
echo "Converting Axiallager_SKF_BA7.STL"
$stl2dae "Axiallager_SKF_BA7.STL" "Axiallager_SKF_BA7.dae" "Steel"
echo "Converting z-potentiometer-wal305-v01.STL"
$stl2dae "z-potentiometer-wal305-v01.STL" "z-potentiometer-wal305-v01.dae" "Steel"
echo "Converting p_NEW_Stift_M6.STL"
$stl2dae "p_NEW_Stift_M6.STL" "p_NEW_Stift_M6.dae" "Steel"
echo "Converting clamping_device_washer_din.STL"
$stl2dae "clamping_device_washer_din.STL" "clamping_device_washer_din.dae" "Steel"
echo "Converting hex_thin_nut_chamfered_gradeab_din.STL"
$stl2dae "hex_thin_nut_chamfered_gradeab_din.STL" "hex_thin_nut_chamfered_gradeab_din.dae" ""
echo "Converting p_NEW_Stift_M5.STL"
$stl2dae "p_NEW_Stift_M5.STL" "p_NEW_Stift_M5.dae" "Steel"
echo "Converting p_NEW_sehne_rot.STL"
$stl2dae "p_NEW_sehne_rot.STL" "p_NEW_sehne_rot.dae" "Steel"
echo "Converting p-Feder_frontal.STL"
$stl2dae "p-Feder_frontal.STL" "p-Feder_frontal.dae" "Steel"
echo "Converting p_NEW_Feder_lateral_GK_D-207J-26.STL"
$stl2dae "p_NEW_Feder_lateral_GK_D-207J-26.STL" "p_NEW_Feder_lateral_GK_D-207J-26.dae" "Steel"
echo "Converting p_NEW_Plaettchen_Induktion.STL"
$stl2dae "p_NEW_Plaettchen_Induktion.STL" "p_NEW_Plaettchen_Induktion.dae" "Steel"
echo "Converting p_NEW_Imduktivsensor.STL"
$stl2dae "p_NEW_Imduktivsensor.STL" "p_NEW_Imduktivsensor.dae" "Steel"
echo "Converting p_NEW_IGUS_GFM-0506-06.STL"
$stl2dae "p_NEW_IGUS_GFM-0506-06.STL" "p_NEW_IGUS_GFM-0506-06.dae" "Steel"
echo "Converting p_NEW_Stift_Hals-Spine.STL"
$stl2dae "p_NEW_Stift_Hals-Spine.STL" "p_NEW_Stift_Hals-Spine.dae" "Steel"
echo "Converting socket_head_cap_screw_din.STL"
$stl2dae "socket_head_cap_screw_din.STL" "socket_head_cap_screw_din.dae" "Steel"
echo "Converting p_NEW_Feder_Rotation.STL"
$stl2dae "p_NEW_Feder_Rotation.STL" "p_NEW_Feder_Rotation.dae" "Steel"
echo "Converting p-Sehneenabschluss.STL"
$stl2dae "p-Sehneenabschluss.STL" "p-Sehneenabschluss.dae" "Steel"
echo "Converting x-EC16-405813-v01.STL"
$stl2dae "x-EC16-405813-v01.STL" "x-EC16-405813-v01.dae" "Steel"
echo "Converting x-gp16-401954-v01.STL"
$stl2dae "x-gp16-401954-v01.STL" "x-gp16-401954-v01.dae" "Steel"
echo "Converting x-motorpulley-v03.STL"
$stl2dae "x-motorpulley-v03.STL" "x-motorpulley-v03.dae" "Steel"
echo "Converting x-motorpulley-ROTATION.STL"
$stl2dae "x-motorpulley-ROTATION.STL" "x-motorpulley-ROTATION.dae" "Steel"
echo "Converting PT35x16.STL"
$stl2dae "PT35x16.STL" "PT35x16.dae" "Steel"
echo "Converting p-torso-v04.STL"
$stl2dae "p-torso-v04.STL" "p-torso-v04.dae" "solidworks_materials_PA_Typ_6_37"
echo "Converting p-halterreferenz-v02.STL"
$stl2dae "p-halterreferenz-v02.STL" "p-halterreferenz-v02.dae" ""
echo "Converting p-halterdeckel-v01.STL"
$stl2dae "p-halterdeckel-v01.STL" "p-halterdeckel-v01.dae" "Steel"
echo "Converting z-getriebe-gp22c-v01.STL"
$stl2dae "z-getriebe-gp22c-v01.STL" "z-getriebe-gp22c-v01.dae" "Steel"
echo "Converting z-EC-max22-283856-v01.STL"
$stl2dae "z-EC-max22-283856-v01.STL" "z-EC-max22-283856-v01.dae" "Steel"
echo "Converting p-absolutmess-plaettchen-v01.STL"
$stl2dae "p-absolutmess-plaettchen-v01.STL" "p-absolutmess-plaettchen-v01.dae" "SolidWorks_DIN_Materials_1.0037_(S235JR)_165"
echo "Converting Hexagon_Thin_Nut_ISO_4035_-_M2.5_-_C.STL"
$stl2dae "Hexagon_Thin_Nut_ISO_4035_-_M2.5_-_C.STL" "Hexagon_Thin_Nut_ISO_4035_-_M2.5_-_C.dae" ""
echo "Converting DIN_912_M2.5_x_16_---_16C.STL"
$stl2dae "DIN_912_M2.5_x_16_---_16C.STL" "DIN_912_M2.5_x_16_---_16C.dae" ""
echo "Converting Sechskantmutter_M4_(BN115).STL"
$stl2dae "Sechskantmutter_M4_(BN115).STL" "Sechskantmutter_M4_(BN115).dae" ""
echo "Converting p-oberarm-1-v02.STL"
$stl2dae "p-oberarm-1-v02.STL" "p-oberarm-1-v02.dae" "Steel"
echo "Converting p-ellenbogenachse-v01.STL"
$stl2dae "p-ellenbogenachse-v01.STL" "p-ellenbogenachse-v01.dae" "SolidWorks_DIN_Materials_1.0037_(S235JR)_165"
echo "Converting p-oberarm-deckel-v01.STL"
$stl2dae "p-oberarm-deckel-v01.STL" "p-oberarm-deckel-v01.dae" "Steel"
echo "Converting z-keramikoese-ek06-132-v01.STL"
$stl2dae "z-keramikoese-ek06-132-v01.STL" "z-keramikoese-ek06-132-v01.dae" "Steel"
echo "Converting nzyl-schr-i6kt-DIN912-M3x8-8.8.STL"
$stl2dae "nzyl-schr-i6kt-DIN912-M3x8-8.8.STL" "nzyl-schr-i6kt-DIN912-M3x8-8.8.dae" ""
echo "Converting z-kugelgriff-v02.STL"
$stl2dae "z-kugelgriff-v02.STL" "z-kugelgriff-v02.dae" "Steel"
echo "Converting p-ulna-v03.STL"
$stl2dae "p-ulna-v03.STL" "p-ulna-v03.dae" "Steel"
echo "Converting p-radius-v02.STL"
$stl2dae "p-radius-v02.STL" "p-radius-v02.dae" "Steel"
echo "Converting p-motorpulley-2-v01.STL"
$stl2dae "p-motorpulley-2-v01.STL" "p-motorpulley-2-v01.dae" "SolidWorks_DIN_Materials_3.0205_(EN-AW_1200)_258"
echo "Converting p-fingerkuppe-12.4.STL"
$stl2dae "p-fingerkuppe-12.4.STL" "p-fingerkuppe-12.4.dae" "Steel"
echo "Converting p-fingerkuppe-18.STL"
$stl2dae "p-fingerkuppe-18.STL" "p-fingerkuppe-18.dae" "Steel"
echo "Converting z-sensor-v01.STL"
$stl2dae "z-sensor-v01.STL" "z-sensor-v01.dae" "Steel"
echo "Converting z-zugfeder-40055.STL"
$stl2dae "z-zugfeder-40055.STL" "z-zugfeder-40055.dae" "Steel"
echo "Converting n-se_schr_in_6kt_din_7991_m03x10.STL"
$stl2dae "n-se_schr_in_6kt_din_7991_m03x10.STL" "n-se_schr_in_6kt_din_7991_m03x10.dae" "Steel"
echo "Converting p-daumen-seg-2-step-v01.STL"
$stl2dae "p-daumen-seg-2-step-v01.STL" "p-daumen-seg-2-step-v01.dae" "Steel"
echo "Converting p-ringfinger-seg-1-step-v02.STL"
$stl2dae "p-ringfinger-seg-1-step-v02.STL" "p-ringfinger-seg-1-step-v02.dae" "Steel"
echo "Converting p-zeigfinger-seg-3-step-v02.STL"
$stl2dae "p-zeigfinger-seg-3-step-v02.STL" "p-zeigfinger-seg-3-step-v02.dae" "Steel"
echo "Converting p-daumen-seg-1-step-v01.STL"
$stl2dae "p-daumen-seg-1-step-v01.STL" "p-daumen-seg-1-step-v01.dae" "Steel"
echo "Converting p-zeigfinger-seg-2-step-v02.STL"
$stl2dae "p-zeigfinger-seg-2-step-v02.STL" "p-zeigfinger-seg-2-step-v02.dae" "Steel"
echo "Converting p-zeigfinger-seg-1-step-v02.STL"
$stl2dae "p-zeigfinger-seg-1-step-v02.STL" "p-zeigfinger-seg-1-step-v02.dae" "Steel"
echo "Converting p-ringfinger-seg-2-step-v02.STL"
$stl2dae "p-ringfinger-seg-2-step-v02.STL" "p-ringfinger-seg-2-step-v02.dae" "Steel"
echo "Converting p-kleinerfinger-seg-2-step-v02.STL"
$stl2dae "p-kleinerfinger-seg-2-step-v02.STL" "p-kleinerfinger-seg-2-step-v02.dae" "Steel"
echo "Converting p-daumen-seg-3-v01.STL"
$stl2dae "p-daumen-seg-3-v01.STL" "p-daumen-seg-3-v01.dae" "Steel"
echo "Converting p-kleinerfinger-seg-1-step-v02.STL"
$stl2dae "p-kleinerfinger-seg-1-step-v02.STL" "p-kleinerfinger-seg-1-step-v02.dae" "Steel"
echo "Converting p-kleinerfinger-seg-3-step-v02.STL"
$stl2dae "p-kleinerfinger-seg-3-step-v02.STL" "p-kleinerfinger-seg-3-step-v02.dae" "Steel"
echo "Converting p-ringfinger-seg-3-step-v02.STL"
$stl2dae "p-ringfinger-seg-3-step-v02.STL" "p-ringfinger-seg-3-step-v02.dae" "Steel"
echo "Converting p-mittelfinger-seg-3-step-v02.STL"
$stl2dae "p-mittelfinger-seg-3-step-v02.STL" "p-mittelfinger-seg-3-step-v02.dae" "Steel"
echo "Converting p-mittelfinger-seg-2-step-v02.STL"
$stl2dae "p-mittelfinger-seg-2-step-v02.STL" "p-mittelfinger-seg-2-step-v02.dae" "Steel"
echo "Converting p-mittelfinger-seg-1-step-v02.STL"
$stl2dae "p-mittelfinger-seg-1-step-v02.STL" "p-mittelfinger-seg-1-step-v02.dae" "Steel"
echo "Converting p-handflaeche-teil-2-v01.STL"
$stl2dae "p-handflaeche-teil-2-v01.STL" "p-handflaeche-teil-2-v01.dae" "Steel"
echo "Converting 121213_PROTOTYP_Kopf-Vorderteil.STL"
$stl2dae "121213_PROTOTYP_Kopf-Vorderteil.STL" "121213_PROTOTYP_Kopf-Vorderteil.dae" "solidworks_materials_ABS_33"
echo "Converting 121213_PROTOTYP_Kopf-Hinterteil.STL"
$stl2dae "121213_PROTOTYP_Kopf-Hinterteil.STL" "121213_PROTOTYP_Kopf-Hinterteil.dae" "Steel"
echo "Converting 121213_PROTOTYP_Ohr-rechts_1.STL"
$stl2dae "121213_PROTOTYP_Ohr-rechts_1.STL" "121213_PROTOTYP_Ohr-rechts_1.dae" "solidworks_materials_ABS_33"
echo "Converting 121213_PROTOTYP_Ohr-links_1.STL"
$stl2dae "121213_PROTOTYP_Ohr-links_1.STL" "121213_PROTOTYP_Ohr-links_1.dae" "solidworks_materials_ABS_33"
echo "Converting Halterung_Kopf_8.STL"
$stl2dae "Halterung_Kopf_8.STL" "Halterung_Kopf_8.dae" "solidworks_materials_Epoxid,_Ungefuellt_234"
echo "Converting Beamer_Optoma_PK320.STL"
$stl2dae "Beamer_Optoma_PK320.STL" "Beamer_Optoma_PK320.dae" "Steel"
echo "Converting Halterung_Beamer.STL"
$stl2dae "Halterung_Beamer.STL" "Halterung_Beamer.dae" "solidworks_materials_ABS_33"
echo "Converting Socket_Head_Cap_Screw_DIN_DIN_912_M2_x_3_---_3N.STL"
$stl2dae "Socket_Head_Cap_Screw_DIN_DIN_912_M2_x_3_---_3N.STL" "Socket_Head_Cap_Screw_DIN_DIN_912_M2_x_3_---_3N.dae" "Steel"
echo "Converting mvBF-MLC-20.04.2010_Default.STL"
$stl2dae "mvBF-MLC-20.04.2010_Default.STL" "mvBF-MLC-20.04.2010_Default.dae" "Steel"
echo "Converting Lensation-SH02M13_Default.STL"
$stl2dae "Lensation-SH02M13_Default.STL" "Lensation-SH02M13_Default.dae" "Steel"
echo "Converting Halterung_Kamera.STL"
$stl2dae "Halterung_Kamera.STL" "Halterung_Kamera.dae" "solidworks_materials_ABS_33"
echo "Converting Halterung_Optik_4.STL"
$stl2dae "Halterung_Optik_4.STL" "Halterung_Optik_4.dae" "solidworks_materials_ABS_33"
echo "Converting CPU.STL"
$stl2dae "CPU.STL" "CPU.dae" "Steel"
echo "Converting speaker.STL"
$stl2dae "speaker.STL" "speaker.dae" "Steel"
echo "Converting p-becken-v04.STL"
$stl2dae "p-becken-v04.STL" "p-becken-v04.dae" "Steel"
echo "Converting p-bein-rechts-v02.STL"
$stl2dae "p-bein-rechts-v02.STL" "p-bein-rechts-v02.dae" "Steel"
echo "Converting p-geometriemodel-bein-rechts-v02.STL"
$stl2dae "p-geometriemodel-bein-rechts-v02.STL" "p-geometriemodel-bein-rechts-v02.dae" "Steel"
echo "Converting p-oberschenkel-huelle-v02.STL"
$stl2dae "p-oberschenkel-huelle-v02.STL" "p-oberschenkel-huelle-v02.dae" "Steel"
echo "Converting p-untrerschenkel-huelle-v02.STL"
$stl2dae "p-untrerschenkel-huelle-v02.STL" "p-untrerschenkel-huelle-v02.dae" "Steel"
echo "Converting p-wirbelsaeule-torso.STL"
$stl2dae "p-wirbelsaeule-torso.STL" "p-wirbelsaeule-torso.dae" "Steel"
echo "Converting p-vorlage-skelett-design-v02.STL"
$stl2dae "p-vorlage-skelett-design-v02.STL" "p-vorlage-skelett-design-v02.dae" "Steel"
echo "Converting a-antriebstrang-ec16-v01-re.STL"
$stl2dae "a-antriebstrang-ec16-v01-re.STL" "a-antriebstrang-ec16-v01-re.dae" "Steel"
echo "Converting a-antriebstrang-ec16-v01-li.STL"
$stl2dae "a-antriebstrang-ec16-v01-li.STL" "a-antriebstrang-ec16-v01-li.dae" "Steel"
echo "Converting baugruppe_oberkoerper_fuer_mep.STL"
$stl2dae "baugruppe_oberkoerper_fuer_mep.STL" "baugruppe_oberkoerper_fuer_mep.dae" "Steel"
